### PR TITLE
made the datamodel for the database, and created a post route for the…

### PR DESCRIPTION
**Pull request by SharjeelSIqbal**
… messages
image

### CODE REVIEW

**Comment by SharjeelSIqbal** [comment]
image

**Review by angeljubilee — COMMENTED** [review]
The api route should be /api/message.  Then you can do a post, get, put, etc on.  Doing a get on /api/sendMessage doesn't sound right.

**Review by angeljubilee — APPROVED** [review]
Looks good

**Review by angeljubilee — COMMENTED** [review]
Looks good

**Pull request merged**
